In [3]:
import pandas as pd

data = pd.read_csv('ks_wells.txt', header='infer', sep=',', delimiter=None)
## data.columns = ["a", "b", "c", "etc."]

In [4]:
data

,KID,API_NUMBER,API_NUM_NODASH,LEASE,WELL,FIELD,LATITUDE,LONGITUDE,LONG_LAT_SOURCE,TOWNSHIP,...,PLUGGING,MODIFIED,OIL_KID,OIL_DOR_ID,GAS_KID,GAS_DOR_ID,KCC_PERMIT,STATUS,STATUS2,COMMENTS
0,1001184201,15-007-20008,1.500720e+13,Kirkbride 'B',1,MEDICINE LODGE NORTH,37.237812,-98.634131,Calc. from footages,32,...,12-MAR-1967,13-JUN-2014,NaN,NaN,NaN,NaN,NaN,D&A,Plugged and Abandoned,NaN
1,1001184206,15-007-20013,1.500720e+13,SLEEPER,1-W,UNNAMED,37.408992,-98.475495,Calc. from footages,30,...,10-JAN-1968,18-APR-2014,NaN,NaN,NaN,NaN,NaN,SWD-P&A,Plugged and Abandoned,NaN
2,1001184249,15-007-20056,1.500720e+13,"Winters, W.W.",1,Aetna Gas Area,37.052861,-98.977851,Calc. from footages,34,...,19-MAR-1968,21-JAN-2014,NaN,NaN,NaN,NaN,NaN,D&A,Plugged and Abandoned,NaN
3,1001184287,15-007-20094,1.500720e+13,Stonestreet,1,WILDCAT,37.313259,-98.710457,Calc. from footages,31,...,11-APR-1969,26-FEB-2015,NaN,NaN,NaN,NaN,NaN,D&A,Plugged and Abandoned,NaN
4,1001184375,15-007-20184,1.500720e+13,Lenkner,1,LUKENS,37.230362,-98.520233,Calc. from footages,32,...,26-NOV-1974,30-OCT-2013,NaN,NaN,NaN,NaN,D16293.0,SWD-P&A,Plugged and Abandoned,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
489895,1046936256,15-009-25779-0002,1.500926e+13,DOONAN A SWD,2,LAKE BARTON,38.459357,-98.766545,From GPS,18,...,NaN,24-JAN-2019,NaN,NaN,NaN,NaN,D32620.0,SWD,Authorized Injection Well,NaN
489896,1046936257,15-059-01620,1.505902e+13,E. SEYLER,ESY 01,NaN,38.669438,-95.186937,From GPS,16,...,17-AUG-2018,04-DEC-2018,NaN,NaN,NaN,NaN,NaN,GAS-P&A,KCC Fee Fund Plugging,NaN
489897,1046936258,15-121-02739,1.512103e+13,KEMPLEY,KEM 01,NaN,38.584086,-94.826890,From GPS,17,...,25-SEP-2018,04-DEC-2018,NaN,NaN,NaN,NaN,NaN,GAS-P&A,KCC Fee Fund Plugging,NaN
489898,1046936259,15-003-26641,1.500327e+13,DONLEY,38,COLONY-WELDA,38.094366,-95.357601,Calc. from footages,22,...,NaN,22-MAY-2019,NaN,NaN,NaN,NaN,NaN,OIL,Inactive Well,NaN
489899,1046936260,15-133-02733,1.513303e+13,MIH,MIH OW1,NaN,37.664181,-95.355999,From GPS,27,...,12-JUL-2018,04-DEC-2018,NaN,NaN,NaN,NaN,NaN,OIL-P&A,KCC Fee Fund Plugging,NaN